def prompt_switch_detection(n_images: int) -> str:
    return (
        f"You are a robotic vision analyzer watching a {n_images}-frame video clip of household manipulation tasks.\n"
        f"**Mapping:** Image indices range from 0 to {n_images - 1}.\n\n"
        "### Goal\n"
        "Detect **task-level boundaries** that are useful for VLA training.\n"
        "Each segment should be one coherent robot instruction from start to finish.\n"
        "Prefer **fewer, cleaner segments** over many tiny segments.\n"
        "A 'Switch' happens when the robot starts a **new goal**, not merely when it briefly touches a new object.\n\n"
        "### Core Logic\n"
        "1. **True Switch:** The previous goal is clearly finished, and the robot begins a different standalone goal.\n"
        "2. **Same Task Across Multiple Objects:** If the robot is still pursuing the same outcome while touching the carried object, a receptacle, a support object, or the final stack, this is **NOT** a switch.\n"
        "3. **Ignore Micro-Adjustments:** Brief nudges, stabilization, re-grasps, post-placement corrections, and tiny follow-up adjustments around the same task are **NOT** new tasks.\n"
        "4. **Preparation Is Part of the Main Task:** Reaching, hovering, aligning, or partially grasping in preparation for the main action should stay inside that same task.\n"
        "5. **When Ambiguous, Merge Rather Than Split.**\n\n"
        "### Output Format: Strict JSON\n"
        "Your response must be a valid JSON object including a 'thought' field for step-by-step analysis, 'transitions' for the switch indices, and 'instructions' for the task labels.\n"
        "Instructions should be concise, task-level, and suitable as robot training commands.\n\n"
        "### Representative Examples\n"
        "**Example 1: Bowl Stacking (False Switch - Same Goal)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-6: Robot grasps and lifts a blue bowl. Frames 7-12: Robot places the blue bowl onto a bowl stack. Frames 13-15: Robot briefly nudges the stack to stabilize it. This is still one coherent stacking task, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Pick up the blue bowl and place it onto the stack\"]\n"
        "}\n\n"
        "**Example 2: Distinct New Goal (True Switch)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-9: Robot finishes placing a bowl onto the stack. Frames 10-11: Gripper leaves the stack. Frames 12-15: Robot reaches to a red cup and begins a new manipulation goal. This is a true task switch at frame 11.\",\n"
        "  \"transitions\": [11],\n"
        "  \"instructions\": [\"Place the bowl onto the stack\", \"Pick up the red cup\"]\n"
        "}\n\n"
        "**Example 3: Preparation + Main Action (Continuous)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-4: Robot hovers and aligns above a cup. Frames 5-15: Robot grasps the cup and moves it to a tray. The early alignment is just preparation for the same task, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Pick up the cup and place it on the tray\"]\n"
        "}"
    )
