def prompt_switch_detection(n_images: int) -> str:
    return (
        f"You are a robotic vision analyzer watching a {n_images}-frame video clip of household manipulation tasks.\n"
        f"**Mapping:** Image indices range from 0 to {n_images - 1}.\n\n"
        "### Goal\n"
        "Detect **task-level boundaries** that are useful for VLA training.\n"
        "Each segment should be one coherent robot instruction from start to finish.\n"
        "Prefer **fewer, cleaner segments** over many tiny segments.\n"
        "A 'Switch' happens when the robot starts a **new goal**, not merely when it briefly touches a new object.\n\n"
        "### Core Logic\n"
        "1. **True Switch:** The previous goal is clearly finished, and the robot begins a different standalone goal.\n"
        "2. **Same Task Across Multiple Objects:** If the robot is still pursuing the same outcome while touching the carried object, a receptacle, a support object, or the final stack, this is **NOT** a switch.\n"
        "3. **Ignore Micro-Adjustments:** Brief nudges, stabilization, re-grasps, post-placement corrections, and tiny follow-up adjustments around the same task are **NOT** new tasks.\n"
        "4. **Preparation Is Part of the Main Task:** Reaching, hovering, aligning, or partially grasping in preparation for the main action should stay inside that same task.\n"
        "5. **Repeated Batch Chores:** Repeating the same high-level chore across several items, such as folding several clothes, plating several dumplings, or adding several ingredients into one bowl, should usually stay as **one segment** unless the goal or work area clearly changes.\n"
        "6. **Different Ingredient / Tool Tasks Can Still Be Separate:** Even in the same salad, bowl, or pot, if the person clearly switches to a sustained new ingredient-focused task with its own preparation, transfer, or tool change, that usually **is** a new task. For example, `slice tomatoes`, `chop basil`, and `grind pepper onto the salad` should usually stay separate.\n"
        "7. **Quick Seasoning Inside The Same Sauce/Dressing Should Stay Merged:** Do **NOT** split quick seasoning, squeezing, whisking, or brief additions when they are part of the same sauce or dressing task in one container. These short same-sauce steps should stay merged unless the work area clearly changes.\n"
        "8. **Ignore Narration / Presentation Shots:** If the person talks to camera, gestures, pauses, or briefly shows the dish while the underlying cooking/manipulation task continues, do **NOT** create a new task.\n"
        "7. **Do NOT output labels like** `Wait`, `Explain the cooking step`, `Explain the recipe`, `Describe the scene`, or other narration-style labels. Always anchor the instruction to the visible manipulation goal.\n"
        "5. **When Ambiguous, Merge Rather Than Split.**\n\n"
        "### Output Format: Strict JSON\n"
        "Your response must be a valid JSON object including a 'thought' field for step-by-step analysis, 'transitions' for the switch indices, and 'instructions' for the task labels.\n"
        "Instructions should be concise, task-level, and suitable as robot training commands.\n\n"
        "### Representative Examples\n"
        "**Example 1: Bowl Stacking (False Switch - Same Goal)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-6: Robot grasps and lifts a blue bowl. Frames 7-12: Robot places the blue bowl onto a bowl stack. Frames 13-15: Robot briefly nudges the stack to stabilize it. This is still one coherent stacking task, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Pick up the blue bowl and place it onto the stack\"]\n"
        "}\n\n"
        "**Example 2: Distinct New Goal (True Switch)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-9: Robot finishes placing a bowl onto the stack. Frames 10-11: Gripper leaves the stack. Frames 12-15: Robot reaches to a red cup and begins a new manipulation goal. This is a true task switch at frame 11.\",\n"
        "  \"transitions\": [11],\n"
        "  \"instructions\": [\"Place the bowl onto the stack\", \"Pick up the red cup\"]\n"
        "}\n\n"
        "**Example 3: Preparation + Main Action (Continuous)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-4: Robot hovers and aligns above a cup. Frames 5-15: Robot grasps the cup and moves it to a tray. The early alignment is just preparation for the same task, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Pick up the cup and place it on the tray\"]\n"
        "}\n\n"
        "**Example 4: Repeated Batch Chores (Still One Segment)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-15: Person folds several clothes one after another on the same table. Although the hands touch multiple garments, the high-level chore is still folding laundry, so keep it as one segment.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Folding several clothes on the table\"]\n"
        "}\n\n"
        "**Example 5: Same Bowl / Same Pot Recipe Assembly (Merge Rather Than Split)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-4: Person adds mayonnaise to a bowl. Frames 5-9: Person adds chopped garlic to the same bowl. Frames 10-15: Person seasons and whisks the bowl mixture. These are consecutive sub-steps of one dressing-making task in the same container, so keep them merged.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Prepare the dressing in the bowl\"]\n"
        "}\n\n"
        "**Example 6: Same Salad, But Distinct Ingredient Tasks (True Switches)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-5: Person slices tomatoes and adds them to the salad. Frames 6-10: Person switches to chopping basil with the knife. Frames 11-15: Person grinds pepper over the salad. Even though everything ends up in the same salad, these are different ingredient-focused tasks with different tools and goals, so keep them separate.\",\n"
        "  \"transitions\": [5, 10],\n"
        "  \"instructions\": [\"Slice tomatoes and add them to the salad\", \"Chop basil and add it to the salad\", \"Grind pepper onto the salad\"]\n"
        "}\n\n"
        "**Example 7: Narration Shot Is Not A Task Boundary**\n"
        "{\n"
        "  \"thought\": \"Frames 0-6: Person chops tomatoes. Frames 7-9: Person looks at the camera and talks briefly. Frames 10-15: Person returns to the same cutting board task. The talking shot is not a new manipulation goal, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Chop the tomatoes on the cutting board\"]\n"
        "}"
    )
